image: php:7.3

stages:
    - build
    - linter
    - test

build:composer:
    stage: build
    script:
        - apt-get update -yq
        - apt-get install git -yq
        - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        - php -r "if (hash_file('sha384', 'composer-setup.php') === 'a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
        - php composer-setup.php
        - php -r "unlink('composer-setup.php');"
        - php composer.phar install
    cache:
        key: "build-${CI_COMMIT_REF_SLUG}"
        paths:
            - vendor/
    artifacts:
        paths:
            - vendor/

lint:phpcs:
    stage: linter
    only:
        changes:
            - .gitlab-ci.yml
            - src
            - tests
    script:
        - vendor/bin/phpcs src
        - vendor/bin/phpcs tests
    dependencies:
        - composer
    cache:
        key: "build-${CI_COMMIT_REF_SLUG}"

tests:unit:
    stage: test
    only:
        changes:
            - .gitlab-ci.yml
            - src
            - tests
    script:
        - vendor/bin/phpunit tests
    dependencies:
        - composer
    cache:
        key: "build-${CI_COMMIT_REF_SLUG}"
