image: php:7.3

stages:
    - build
    - test

build:
    stage: build
    script:
        - apt-get update -yq
        - apt-get install git -yq
        - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        - php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
        - php composer-setup.php
        - php -r "unlink('composer-setup.php');"
        - php composer.phar install
    cache:
        key: "build-${CI_COMMIT_REF_SLUG}"
        paths:
            - vendor/
    artifacts:
        paths:
            - vendor/

lint:phpcs:
    stage: test
    script:
        - vendor/bin/phpcs src
        - vendor/bin/phpcs tests
    dependencies:
        - build
    cache:
        key: "build-${CI_COMMIT_REF_SLUG}"

tests:unit:
    stage: test
    script:
        - vendor/bin/phpunit tests
    dependencies:
        - build
    cache:
        key: "build-${CI_COMMIT_REF_SLUG}"

tests:coverage:
    stage: test
    script:
        - pecl install xdebug
        - docker-php-ext-enable xdebug
        - vendor/bin/phpunit --coverage-text --colors=never tests
    dependencies:
        - build
    cache:
        key: "build-${CI_COMMIT_REF_SLUG}"
